### ISSUE TITLE
BUG: Build failure on Python 3.14 due to `ast` changes

### ISSUE THREAD

**Issue by sarahec** [langchain-ai/langchain-community#492]
### Checked other resources

- [x] This is a bug, not a usage question.
- [x] I added a clear and descriptive title that summarizes this issue.
- [x] I used the GitHub search to find a similar question and didn't find it.
- [x] I am sure that this is a bug in LangChain Community rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain Community.
- [x] I read what a minimal reproducible example is (https://stackoverflow.com/help/minimal-reproducible-example).
- [x] I posted a self-contained, minimal, reproducible example. A maintainer can copy it and run it AS IS.

### Example Code

While building for python 3.14 on nixpkgs:
`FAILED tests/unit_tests/test_imports.py::test_no_dynamic__all__ - AttributeError: module 'ast' has no attribute 'Str'`

### Description

* I'm building langchain-community @ 0.4.1 on python 3.14 and hitting a test error.
* No action needed immediately, I've disabled the failing import test. This is a courtesy notice.

**Comment by sarahec** [comment]
Note: `langchain-experimental` @ 0.4.1 fails in the same way:

> FAILED tests/unit_tests/test_pal.py::test_color_question_1 - AttributeError: module 'ast' has no attribute 'Str'
> FAILED tests/unit_tests/test_pal.py::test_color_question_2 - AttributeError: module 'ast' has no attribute 'Str'

**Comment by CrepuscularIRIS** [comment]
Hi — I'd like to submit a fix for this.

Root cause is in `libs/community/tests/unit_tests/test_imports.py:60`: `_check_correct_or_not_defined__all__` uses `ast.Str` to verify that `__all__` entries are string literals. `ast.Str` has been deprecated since 3.8 and removed in 3.14, which is why the import is raising `AttributeError: module 'ast' has no attribute 'Str'`.

Plan: replace the single `ast.Str` check with `isinstance(el, ast.Constant) and isinstance(el.value, str)`, which behaves the same on the existing 3.10–3.13 supported versions and works on 3.14. No production code uses the deprecated aliases — I grepped the repo and this test helper is the only site. I'll add a small parametrised assertion that `_check_correct_or_not_defined__all__` still accepts literal `__all__ = ["x", "y"]` and rejects non-string entries, so the behaviour stays locked in.

Would this be welcome as a small PR?

**Comment by mdrxy** [comment]
Thank you for filing this! As announced in #674, the `langchain-community` package is being sunset, and we are closing the open issues as part of that wind-down.

For context and next steps (including how to create a standalone integration package), please see https://github.com/langchain-ai/langchain-community/issues/674.

We truly appreciate the time you took to report this — thank you.
